/* eslint-disable */

/**
 * Generated by @openapi-codegen
 *
 * @version 0.0.0
 */
export type Book = {
  /**
   * @format uuid
   */
  id: string;
  /**
   * @maxLength 20
   */
  title: string;
  price?: number | null;
};

export type PatchedBook = {
  /**
   * @format uuid
   */
  id?: string;
  /**
   * @maxLength 20
   */
  title?: string;
  price?: number | null;
};
